version: '3.7'
name: task
networks:
    task_net:
        driver: bridge
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: server
        container_name: task_server
        networks:
            - task_net
        links:
            - mysql
        depends_on:
            - mysql
        ports:
            - ${SERVER_PORT}:80
        volumes:
            - ../:/var/www/html
        environment:
            DB_HOST: task_mysql
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            SERVER_PORT: ${SERVER_PORT}
    mysql:
        image: mysql:8
        container_name: task_mysql
        command: --max_allowed_packet=92505856
        networks:
            - task_net
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./data/mysql:/var/lib/mysql